CREATE DATABASE QUANLYBIDA
GO

USE QUANLYBIDA
GO

CREATE TABLE LOAIBAN
(
	ID_LOAIBAN INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(100) NOT NULL,
	GIA FLOAT
)
GO

CREATE TABLE BAN
(
	ID_BAN INT IDENTITY(1,1) PRIMARY KEY,
	TENBAN NVARCHAR(100),
	TRANGTHAI BIT NOT NULL,
	GIOVAO DATETIME,
	GIORA DATETIME,
	ID_LOAIBAN INT REFERENCES LOAIBAN(ID_LOAIBAN)
)
GO

CREATE TABLE LOAITHUCPHAM
(
	ID_LOAITHUCPHAM INT IDENTITY PRIMARY KEY,
	TENLOAITHUCPHAM NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE NHACUNGCAP
(
	ID_NHACUNGCAP INT IDENTITY PRIMARY KEY,
	TENNHACUNGCAP NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE THUCPHAM
(
	ID_THUCPHAM INT IDENTITY PRIMARY KEY,
	TENTHUCPHAM NVARCHAR(100) NOT NULL,
	DVT NVARCHAR(100),
	ID_LOAITHUCPHAM INT REFERENCES LOAITHUCPHAM(ID_LOAITHUCPHAM) NOT NULL,
	SOLUONG INT,
	GIABAN FLOAT,
	ID_NHACUNGCAP INT REFERENCES NHACUNGCAP(ID_NHACUNGCAP)
	
)
GO
CREATE TABLE DANGNHAP
(
	TENDANGNHAP NVARCHAR(100) PRIMARY KEY,
	MATKHAU NVARCHAR(1000) NOT NULL
)
GO
CREATE TABLE CAPBAC
(
	ID_CAPBAC INT IDENTITY PRIMARY KEY,
	TENCAPBAC NVARCHAR(100) NOT NULL,
	HESOLUONG FLOAT
)
GO
CREATE TABLE NHANVIEN
(
	ID_NHANVIEN INT IDENTITY PRIMARY KEY,
	TENNHANVIEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	CMND NVARCHAR(100) NOT NULL,
	SODIENTHOAI NVARCHAR(100),
	GIOITINH BIT,
	ID_CAPBAC INT REFERENCES CAPBAC(ID_CAPBAC),
	CATRUC NVARCHAR(100),
	TENDANGNHAP NVARCHAR(100) REFERENCES DANGNHAP(TENDANGNHAP)
)
GO
CREATE TABLE LOAIKHACHHANG
(
	ID_LOAIKHACHHANG INT IDENTITY PRIMARY KEY,
	TENLOAIKHACHHANG NVARCHAR(100),
	GIAMGIAGIO FLOAT,
	GIAMGIATHUCPHAM FLOAT,
)
GO
CREATE TABLE KHACHHANG
(
	ID_KHACHHANG INT IDENTITY PRIMARY KEY,
	TENKHACHHANG NVARCHAR(100) NOT NULL,
	SODIENTHOAI NVARCHAR(100),
	NGAYSINH DATETIME,
	GIOITINH BIT,
	GUICO BIT NOT NULL,
	ID_LOAIKHACHHANG INT REFERENCES LOAIKHACHHANG(ID_LOAIKHACHHANG)
)
GO
CREATE TABLE GIAMGIA
(
	ID_GIAMGIA INT IDENTITY(1,1) PRIMARY KEY,
	TENGIAMGIA NVARCHAR(100) NOT NULL,
	GIAMGIAGIO FLOAT,
	GIAMGIATHUCPHAM FLOAT,
	NGAYBATDAU datetime,
	NGAYKETTHUC datetime
)
GO
CREATE TABLE HOADON
(
	ID_HOADON INT IDENTITY PRIMARY KEY,
	ID_BAN INT REFERENCES BAN(ID_BAN),
	ID_NHANVIEN INT REFERENCES NHANVIEN(ID_NHANVIEN),
	ID_KHACHHANG INT REFERENCES KHACHHANG(ID_KHACHHANG),
	ID_GIAMGIA INT REFERENCES GIAMGIA(ID_GIAMGIA),
	GIAMGIAGIO FLOAT,
	GIAMGIATHUCPHAM FLOAT,
	TONGGIOCHOI datetime,
	DATHANHTOAN BIT
)
GO
CREATE TABLE CHITIETHD
(
	ID_HOADON INT REFERENCES HOADON(ID_HOADON),
	ID_THUCPHAM INT REFERENCES THUCPHAM(ID_THUCPHAM),
	SOLUONG INT
	CONSTRAINT KHOA_CTHD PRIMARY KEY(ID_HOADON,ID_THUCPHAM)
)
GO
CREATE TABLE QUYEN
(
	ID_QUYEN INT IDENTITY(1,1) PRIMARY KEY,
	TENQUYEN NVARCHAR(100)
)
GO
CREATE TABLE PHANQUYEN
(
	ID_QUYEN INT REFERENCES QUYEN(ID_QUYEN),
	ID_CAPBAC INT REFERENCES CAPBAC(ID_CAPBAC),
	CONSTRAINT KHOA_PHANQUYEN PRIMARY KEY(ID_QUYEN,ID_CAPBAC)
)
GO
CREATE TABLE HOADONNHAP
(
	ID_HOADONNHAP INT IDENTITY(1,1) PRIMARY KEY,
	ID_TENHOADONNHAP NVARCHAR(100),
	NGAYNHAP DATETIME
)
GO
CREATE TABLE CHITIET_HOADONNHAP
(
	ID_HOADONNHAP INT REFERENCES HOADONNHAP(ID_HOADONNHAP),
	ID_THUCPHAM INT REFERENCES THUCPHAM(ID_THUCPHAM),
	CONSTRAINT KHOA_CHITIETNHAP PRIMARY KEY(ID_HOADONNHAP,ID_THUCPHAM),
	SOLUONG INT,
	GIANHAP FLOAT
)
GO
CREATE TABLE LUONG
(
	ID_LUONG INT IDENTITY(1,1) PRIMARY KEY,
	ID_NHANVIEN INT REFERENCES NHANVIEN(ID_NHANVIEN),
	SONGAYCONG INT,
	PHUCAP FLOAT,
	THUONG FLOAT,
	PHAT FLOAT
)
GO
-- insert Data
insert into DANGNHAP 
values ('admin','');
GO

INSERT INTO LOAIBAN (TENLOAI,GIA)
VALUES ('FRANCE',40000)
GO
INSERT INTO LOAIBAN (TENLOAI,GIA)
VALUES ('POOL',60000)
GO
INSERT INTO LOAIBAN (TENLOAI,GIA)
VALUES ('CAROM',80000)
GO


-- INSERT
DECLARE @i int = 0
while @i < 10
begin
	INSERT INTO BAN(TENBAN,TRANGTHAI,GIOVAO,GIORA,ID_LOAIBAN)
	VALUES ('FRANCE '+ cast(@i as nvarchar(100)),0,NULL,NULL,1)
	set @i =@i+1
end
go
INSERT INTO LOAITHUCPHAM
VALUES (N'Thức ăn')
GO
INSERT INTO LOAITHUCPHAM
VALUES (N'Cà phê')
GO
INSERT INTO LOAITHUCPHAM
VALUES (N'Bia')
GO
-- Insert NHACUNGCAP
insert into NHACUNGCAP
values (N'CocaCola')
go
insert into NHACUNGCAP
values (N'Khac')
go

-- Insert THUCPHAM

insert into THUCPHAM
values (N'Mì tôm trứng',N'Tô',1,35000,1)
go
insert into dbo.THUCPHAM
values (N'Cơm tấm sài gòn',N'Dĩa',1,50000,1)
go
insert into dbo.THUCPHAM
values (N'Nước chanh',N'Ly',2,35000,2)
go
insert into dbo.THUCPHAM
values (N'Budweiser',N'Chai',3,27000,2)
go

-- INSERT LOAI KHACH HANG
INSERT INTO LOAIKHACHHANG VALUES (N'Thường',0,0)
INSERT INTO LOAIKHACHHANG VALUES (N'Vip 1',0.2,0)
INSERT INTO LOAIKHACHHANG VALUES (N'Vip 2',0.3,0.2)
-- INSERT KHACHHANG
INSERT INTO KHACHHANG VALUES(N'Nguyễn Văn A','01223948242',convert(datetime,'25/4/1997',103),1,0,1)
INSERT INTO KHACHHANG VALUES(N'Nguyễn Văn B','01223948242',convert(datetime,'25/4/1997',103),1,0,2)
INSERT INTO KHACHHANG VALUES(N'Nguyễn Văn C','01223948242',convert(datetime,'25/4/1997',103),1,0,3)
-- INSERT INTO CAPBAC
INSERT INTO CAPBAC VALUES(N'Nhân viên',80000)
INSERT INTO CAPBAC VALUES(N'Thu Ngân',100000)
INSERT INTO CAPBAC VALUES(N'Thủ Kho',100000)
INSERT INTO CAPBAC VALUES(N'Quản lý',240000)
-- INSERT NHANVIEN
INSERT INTO NHANVIEN VALUES(N'Nguyễn Hữu Định',convert(datetime,'25/4/1997',103),'164132198','2984132',1,1,'Tối',null)
INSERT INTO NHANVIEN VALUES(N'Huỳnh Nhựt',convert(datetime,'25/4/1997',103),'164132198','2984132',2,1,'Tối',null)
INSERT INTO NHANVIEN VALUES(N'Phan Thanh Tú',convert(datetime,'25/4/1997',103),'164132198','2984132',3,1,'Tối',null)
INSERT INTO NHANVIEN VALUES(N'Nguyễn Quốc Vương',convert(datetime,'25/4/1997',103),'164132198','2984132',4,1,'Tối',null)

-- INSERT GIAMGIA
INSERT INTO GIAMGIA VALUES(N'Sinh nhật quán',0.5,0.5)
INSERT INTO GIAMGIA VALUES(N'Không Giảm giá',0,0)

-- INSERT HOADON
SELECT * FROM HOADON
INSERT INTO HOADON(ID_BAN,ID_NHANVIEN,ID_KHACHHANG,ID_GIAMGIA,GIAMGIAGIO,GIAMGIATHUCPHAM,TONGGIOCHOI,DATHANHTOAN)
VALUES (3,null,null,null,null,null,convert(datetime,'03:02',103),0)
INSERT INTO HOADON(ID_BAN,ID_NHANVIEN,ID_KHACHHANG,ID_GIAMGIA,GIAMGIAGIO,GIAMGIATHUCPHAM,TONGGIOCHOI,DATHANHTOAN)
VALUES (3,null,null,null,null,null,convert(datetime,'01:00',103),1)
INSERT INTO HOADON(ID_BAN,ID_NHANVIEN,ID_KHACHHANG,ID_GIAMGIA,GIAMGIAGIO,GIAMGIATHUCPHAM,TONGGIOCHOI,DATHANHTOAN)
VALUES (2,null,null,null,null,null,0,0)
-- INSERT CTHOADON
DELETE HOADON
